export const EMPLOYEES = [
  {
    id: 0,
    salary: 13147,
    name: "Marie Snyder",
    department: "HR",
  },
  {
    id: 1,
    salary: 43899,
    name: "Maricela Dunlap",
    department: "PS",
  },
  {
    id: 2,
    salary: 6137,
    name: "Cameron Henderson",
    department: "HR",
  },
  {
    id: 3,
    salary: 37068,
    name: "Hammond Fernandez",
    department: "HR",
  },
  {
    id: 4,
    salary: 31591,
    name: "Odom Golden",
    department: "PS",
  },
  {
    id: 5,
    salary: 400,
    name: "Lara Haley",
    department: "HR",
  },
  {
    id: 6,
    salary: 7600,
    name: "Hull Gay",
    department: "PS",
  },
  {
    id: 7,
    salary: 42444,
    name: "Alexis Eaton",
    department: "PS",
  },
  {
    id: 8,
    salary: 16935,
    name: "Carmen Rodriguez",
    department: "HR",
  },
  {
    id: 9,
    salary: 336,
    name: "Ayers Jennings",
    department: "PS",
  },
  {
    id: 10,
    salary: 40378,
    name: "Workman Strickland",
    department: "HR",
  },
  {
    id: 11,
    salary: 35393,
    name: "Georgette Finch",
    department: "HR",
  },
  {
    id: 12,
    salary: 31434,
    name: "Malinda Lee",
    department: "HR",
  },
  {
    id: 13,
    salary: 35171,
    name: "Villarreal Montoya",
    department: "PS",
  },
  {
    id: 14,
    salary: 42432,
    name: "Juarez Butler",
    department: "PS",
  },
  {
    id: 15,
    salary: 29520,
    name: "Patricia Blankenship",
    department: "HR",
  },
  {
    id: 16,
    salary: 21332,
    name: "Buckner Harrell",
    department: "PS",
  },
  {
    id: 17,
    salary: 12743,
    name: "Tyler Hunter",
    department: "PS",
  },
  {
    id: 18,
    salary: 1350,
    name: "Bender Bowman",
    department: "PS",
  },
  {
    id: 19,
    salary: 48076,
    name: "Elise Sweet",
    department: "HR",
  },
  {
    id: 20,
    salary: 3005,
    name: "Olson Hardy",
    department: "PS",
  },
  {
    id: 21,
    salary: 41258,
    name: "Spears Carroll",
    department: "HR",
  },
  {
    id: 22,
    salary: 37797,
    name: "Esperanza Jensen",
    department: "PS",
  },
  {
    id: 23,
    salary: 43663,
    name: "Madelyn Nixon",
    department: "HR",
  },
  {
    id: 24,
    salary: 32111,
    name: "Guerra Cleveland",
    department: "PS",
  },
  {
    id: 25,
    salary: 44940,
    name: "Faith Robbins",
    department: "HR",
  },
  {
    id: 26,
    salary: 7384,
    name: "Dona Perry",
    department: "HR",
  },
  {
    id: 27,
    salary: 43278,
    name: "Moss Rowe",
    department: "HR",
  },
  {
    id: 28,
    salary: 8626,
    name: "Danielle Johns",
    department: "PS",
  },
  {
    id: 29,
    salary: 35107,
    name: "Mckinney Rogers",
    department: "HR",
  },
  {
    id: 30,
    salary: 14614,
    name: "Ashley Moran",
    department: "PS",
  },
  {
    id: 31,
    salary: 6259,
    name: "Ingrid Burns",
    department: "PS",
  },
  {
    id: 32,
    salary: 41819,
    name: "Mayer Webb",
    department: "HR",
  },
  {
    id: 33,
    salary: 38657,
    name: "Patsy Nolan",
    department: "HR",
  },
  {
    id: 34,
    salary: 13837,
    name: "Diane Munoz",
    department: "PS",
  },
  {
    id: 35,
    salary: 1541,
    name: "Mollie Mcconnell",
    department: "HR",
  },
  {
    id: 36,
    salary: 26772,
    name: "Emilia Santana",
    department: "PS",
  },
  {
    id: 37,
    salary: 38596,
    name: "Phoebe Chapman",
    department: "HR",
  },
  {
    id: 38,
    salary: 39853,
    name: "Della Cook",
    department: "HR",
  },
  {
    id: 39,
    salary: 9362,
    name: "Geneva Walters",
    department: "PS",
  },
  {
    id: 40,
    salary: 4137,
    name: "Ursula Maxwell",
    department: "PS",
  },
  {
    id: 41,
    salary: 25368,
    name: "Lane Gates",
    department: "PS",
  },
  {
    id: 42,
    salary: 27227,
    name: "Elinor Oneal",
    department: "HR",
  },
  {
    id: 43,
    salary: 49020,
    name: "Frazier Duncan",
    department: "PS",
  },
  {
    id: 44,
    salary: 32013,
    name: "Terrie Keller",
    department: "PS",
  },
  {
    id: 45,
    salary: 2040,
    name: "Chavez Mosley",
    department: "HR",
  },
  {
    id: 46,
    salary: 41740,
    name: "Kaye Acosta",
    department: "HR",
  },
  {
    id: 47,
    salary: 40757,
    name: "Leila Harrison",
    department: "PS",
  },
  {
    id: 48,
    salary: 7335,
    name: "Latasha Schneider",
    department: "HR",
  },
  {
    id: 49,
    salary: 25516,
    name: "Johnnie Garcia",
    department: "PS",
  },
];
