import { DEPARTMENT, employee } from "./EmployeeCard";

export const SAMPLE_EMPLOYEES: employee[] = [
  {
    id: 0,
    salary: 13147,
    name: "Marie Snyder",
    department: DEPARTMENT.HR,
  },
  {
    id: 1,
    salary: 43899,
    name: "Maricela Dunlap",
    department: DEPARTMENT.PS,
  },
  {
    id: 2,
    salary: 6137,
    name: "Cameron Henderson",
    department: DEPARTMENT.HR,
  },
  {
    id: 3,
    salary: 37068,
    name: "Hammond Fernandez",
    department: DEPARTMENT.HR,
  },
  {
    id: 4,
    salary: 31591,
    name: "Odom Golden",
    department: DEPARTMENT.PS,
  },
  {
    id: 5,
    salary: 400,
    name: "Lara Haley",
    department: DEPARTMENT.HR,
  },
  {
    id: 6,
    salary: 7600,
    name: "Hull Gay",
    department: DEPARTMENT.PS,
  },
  {
    id: 7,
    salary: 42444,
    name: "Alexis Eaton",
    department: DEPARTMENT.PS,
  },
  {
    id: 8,
    salary: 16935,
    name: "Carmen Rodriguez",
    department: DEPARTMENT.HR,
  },
  {
    id: 9,
    salary: 336,
    name: "Ayers Jennings",
    department: DEPARTMENT.PS,
  },
  {
    id: 10,
    salary: 40378,
    name: "Workman Strickland",
    department: DEPARTMENT.HR,
  },
  {
    id: 11,
    salary: 35393,
    name: "Georgette Finch",
    department: DEPARTMENT.HR,
  },
  // {
  //   id: 12,
  //   salary: 31434,
  //   name: "Malinda Lee",
  //   department: DEPARTMENT.HR,
  // },
  // {
  //   id: 13,
  //   salary: 35171,
  //   name: "Villarreal Montoya",
  //   department: DEPARTMENT.PS,
  // },
  // {
  //   id: 14,
  //   salary: 42432,
  //   name: "Juarez Butler",
  //   department: DEPARTMENT.PS,
  // },
  // {
  //   id: 15,
  //   salary: 29520,
  //   name: "Patricia Blankenship",
  //   department: DEPARTMENT.HR,
  // },
  // {
  //   id: 16,
  //   salary: 21332,
  //   name: "Buckner Harrell",
  //   department: DEPARTMENT.PS,
  // },
  // {
  //   id: 17,
  //   salary: 12743,
  //   name: "Tyler Hunter",
  //   department: DEPARTMENT.PS,
  // },
  // {
  //   id: 18,
  //   salary: 1350,
  //   name: "Bender Bowman",
  //   department: DEPARTMENT.PS,
  // },
  // {
  //   id: 19,
  //   salary: 48076,
  //   name: "Elise Sweet",
  //   department: DEPARTMENT.HR,
  // },
  // {
  //   id: 20,
  //   salary: 3005,
  //   name: "Olson Hardy",
  //   department: DEPARTMENT.PS,
  // },
  // {
  //   id: 21,
  //   salary: 41258,
  //   name: "Spears Carroll",
  //   department: DEPARTMENT.HR,
  // },
  // {
  //   id: 22,
  //   salary: 37797,
  //   name: "Esperanza Jensen",
  //   department: DEPARTMENT.PS,
  // },
  // {
  //   id: 23,
  //   salary: 43663,
  //   name: "Madelyn Nixon",
  //   department: DEPARTMENT.HR,
  // },
  // {
  //   id: 24,
  //   salary: 32111,
  //   name: "Guerra Cleveland",
  //   department: DEPARTMENT.PS,
  // },
  // {
  //   id: 25,
  //   salary: 44940,
  //   name: "Faith Robbins",
  //   department: DEPARTMENT.HR,
  // },
  // {
  //   id: 26,
  //   salary: 7384,
  //   name: "Dona Perry",
  //   department: DEPARTMENT.HR,
  // },
  // {
  //   id: 27,
  //   salary: 43278,
  //   name: "Moss Rowe",
  //   department: DEPARTMENT.HR,
  // },
  // {
  //   id: 28,
  //   salary: 8626,
  //   name: "Danielle Johns",
  //   department: DEPARTMENT.PS,
  // },
  // {
  //   id: 29,
  //   salary: 35107,
  //   name: "Mckinney Rogers",
  //   department: DEPARTMENT.HR,
  // },
  // {
  //   id: 30,
  //   salary: 14614,
  //   name: "Ashley Moran",
  //   department: DEPARTMENT.PS,
  // },
  // {
  //   id: 31,
  //   salary: 6259,
  //   name: "Ingrid Burns",
  //   department: DEPARTMENT.PS,
  // },
  // {
  //   id: 32,
  //   salary: 41819,
  //   name: "Mayer Webb",
  //   department: DEPARTMENT.HR,
  // },
  // {
  //   id: 33,
  //   salary: 38657,
  //   name: "Patsy Nolan",
  //   department: DEPARTMENT.HR,
  // },
  // {
  //   id: 34,
  //   salary: 13837,
  //   name: "Diane Munoz",
  //   department: DEPARTMENT.PS,
  // },
  // {
  //   id: 35,
  //   salary: 1541,
  //   name: "Mollie Mcconnell",
  //   department: DEPARTMENT.HR,
  // },
  // {
  //   id: 36,
  //   salary: 26772,
  //   name: "Emilia Santana",
  //   department: DEPARTMENT.PS,
  // },
  // {
  //   id: 37,
  //   salary: 38596,
  //   name: "Phoebe Chapman",
  //   department: DEPARTMENT.HR,
  // },
  // {
  //   id: 38,
  //   salary: 39853,
  //   name: "Della Cook",
  //   department: DEPARTMENT.HR,
  // },
  // {
  //   id: 39,
  //   salary: 9362,
  //   name: "Geneva Walters",
  //   department: DEPARTMENT.PS,
  // },
  // {
  //   id: 40,
  //   salary: 4137,
  //   name: "Ursula Maxwell",
  //   department: DEPARTMENT.PS,
  // },
  // {
  //   id: 41,
  //   salary: 25368,
  //   name: "Lane Gates",
  //   department: DEPARTMENT.PS,
  // },
  // {
  //   id: 42,
  //   salary: 27227,
  //   name: "Elinor Oneal",
  //   department: DEPARTMENT.HR,
  // },
  // {
  //   id: 43,
  //   salary: 49020,
  //   name: "Frazier Duncan",
  //   department: DEPARTMENT.PS,
  // },
  // {
  //   id: 44,
  //   salary: 32013,
  //   name: "Terrie Keller",
  //   department: DEPARTMENT.PS,
  // },
  // {
  //   id: 45,
  //   salary: 2040,
  //   name: "Chavez Mosley",
  //   department: DEPARTMENT.HR,
  // },
  // {
  //   id: 46,
  //   salary: 41740,
  //   name: "Kaye Acosta",
  //   department: DEPARTMENT.HR,
  // },
  // {
  //   id: 47,
  //   salary: 40757,
  //   name: "Leila Harrison",
  //   department: DEPARTMENT.PS,
  // },
  // {
  //   id: 48,
  //   salary: 7335,
  //   name: "Latasha Schneider",
  //   department: DEPARTMENT.HR,
  // },
  // {
  //   id: 49,
  //   salary: 25516,
  //   name: "Johnnie Garcia",
  //   department: DEPARTMENT.PS,
  // },
];
